spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product  # Correct URL scheme
    username: postgres
    password: Sujith@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    url: jdbc:postgresql://localhost:5432/product  # Explicit Flyway URL
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8050
